site_name: unix.rs
site_url: https://unix.rs
site_dir: public
docs_dir: ./docs

watch:
  - includes

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes
    - navigation.instant
    - content.code.annotate
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - footnotes
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - tags
  - git-revision-date-localized:
      type: datetime
      timezone: "Europe/Amsterdam"
      enable_creation_date: true