site_name: unix.rs
site_url: https://unix.rs
site_dir: public
docs_dir: ./docs

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes
    - navigation.instant
    - content.code.annotate

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - tags
  - git-revision-date-localized