name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
      run: mkdocs build --strict --verbose
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "public/"
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      usess: actions/deploy-pages@v4
      with:
        token: ${{github.token}}

        